version: '3'
services:
  web:
    build: .
    command: npm start
    ports:
      - "3030:3030"
    env_file: .env
    depends_on:
      - db
    environment:
      - DB_HOST=db
  db:
    image: postgres:latest
    volumes:
      - /opt/gradissue-2017/db:/var/lib/postgresql/
    ports:
      - "5432"
    env_file: .env
    restart: always